spring:
  datasource:
    url: jdbc:mysql://localhost:3306/safe_route_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mappers/*.xml
